version: '3.1'

services:

  redis_service:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - ./redisdb:/data

  web:
    build: .
    container_name: "flask_application"
    ports:
      - "5050:5000"
    command: flask run --host 0.0.0.0 -p 5000
    environment:
      - FLASK_APP=main.py
    depends_on:
      - "redis_service"