# -*- coding: utf-8 -*-
"""Task_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e80zrqSakUzbs6WBUWfFpua3FpdDLfVU
"""

def iki_defe_artir(num):
    return num*2
a=[1,2,3,4]
b=[]
b=map(iki_defe_artir,a)
print(list(b))

numbers=[100,21,53,44]
result = list(filter(lambda num: num%2==0,numbers))
print(result)

def unique_list(l):
  x = []
  for a in l:
    if a not in x:
      x.append(a)
  return x

print(unique_list([1,2,3,3,3,3,4,5]))

